[workspace]
members = ["macros"]

[package]
name = "parlance"
version = "0.1.0"
edition = "2021"

[dependencies]
parlance-macros = { version = "0.1.0", path = "macros" }
paste = "1.0.15"
thiserror = "2.0.11"

[dev-dependencies]
proptest = "1.6.0"

[features]
case_sensitive_tags = []
case_insensitive_tags = []
complete_tags = []
partial_tags = []
